package gov.dhs.uscis.td.domain;

import java.util.Date;

public class Greeting {

  private final String message;
  private final Date date;
  private final String author;
  private final String guestbook;

  /**
   * A POJO representing a message in a guestbook.
   * 
   * @param message The message in the guestbook.
   * @param date The date and time the message was posted.
   * @param author The author of the message.
   * @param guestbook The name of the guestbook.
   */
  public Greeting(String message, Date date, String author, String guestbook) {
    this.message = message;
    this.date = date;
    this.author = author;
    this.guestbook = guestbook;
  }

  public String getMessage() {
    return message;
  }

  public Date getDate() {
    return date;
  }

  public String getAuthor() {
    return author;
  }

  public String getGuestbook() {
    return guestbook;
  }

  @Override
  public boolean equals(Object obj) {
    // Autogenerated.
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    Greeting other = (Greeting) obj;
    if (author == null) {
      if (other.author != null) {
        return false;
      }
    } else if (!author.equals(other.author)) {
      return false;
    }
    if (date == null) {
      if (other.date != null) {
        return false;
      }
    } else if (!date.equals(other.date)) {
      return false;
    }
    if (guestbook == null) {
      if (other.guestbook != null) {
        return false;
      }
    } else if (!guestbook.equals(other.guestbook)) {
      return false;
    }
    if (message == null) {
      if (other.message != null) {
        return false;
      }
    } else if (!message.equals(other.message)) {
      return false;
    }
    return true;
  }

}
